//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberClub_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prices()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int PriceID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Days Days { get; set; }
        public virtual Periods Periods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
