//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberClub_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PriceID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime SaleTime { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Prices Prices { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
